apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api
spec:
  selector:
    app: ecommerce-api
  ports:
    - protocol: TCP
      port: 8080  # Expose port 8080 for your app
      targetPort: 8080
  type: ClusterIP  # Internal service within the cluster
