apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1  # Running a single instance of PostgreSQL
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:  # Correct field name
        - name: POSTGRES_USER
          value: "yourusername"  # Replace with your actual DB username
        - name: POSTGRES_PASSWORD
          value: "yourpassword"  # Replace with your actual DB password
        - name: POSTGRES_DB
          value: "yourdatabase"  # Replace with your actual DB name
        ports:
        - containerPort: 5432
